config/routes.rb
Project5::Application.routes.draw do

  root  to: "index#index"
  resources :algorithms
  resources :maps
  resources :routes
  get '/routes/map/new/:id' => 'routes#new'
  get '/routes/map/:id' => 'routes#index'
  get '/algorithms/new/:id' => 'algorithms#new'
  post '/algorithms/create/' => 'algorithms#create'

end

app/models/algorithm.rb
class Algorithm < ActiveRecord::Base
      attr_accessible :form_autonomy, :form_cost, :form_source, :form_target, :form_total, :map_id
      validates_presence_of :map_id, :form_source, :form_target, :form_autonomy, :form_cost
end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name
  has_many :routes
end

app/models/route.rb
class Route < ActiveRecord::Base
  attr_accessible :distance, :map_id, :source, :target
  validates_presence_of :distance, :map_id, :source, :target
  belongs_to :map
end

app/controllers/algorithms_controller.rb
class AlgorithmsController < ApplicationController

      #This function redirects to the view new
      def new

      end

      #This function call the dijkstra algorithm, make a new instance of Algorithm
      #calculate de smaller distance and the path to it.
      def create
            @algorithm = Algorithm.create(algorithm_params)

            if @algorithm.save
                  require_relative '../../lib/dijkstra.rb'
                  @routes = Route.where(map_id: @algorithm.map_id)

                  @graph = Graph.new
                  (1..6).each {|node| @graph.push node }

                  @routes.each do |route|
                        @graph.connect_mutually route.source.to_i, route.target.to_i, route.distance.to_i
                  end

                  @graph
                  @graph.length_between(@algorithm.form_source.to_i, @algorithm.form_target.to_i)
                  @graph.neighbors(@algorithm.form_source.to_i)


                  minimum_distance = @graph.dijkstra(@algorithm.form_source.to_i, @algorithm.form_target.to_i)[:distance]

                  @algorithm.form_total = (minimum_distance/@algorithm.form_autonomy) * @algorithm.form_cost
            else
                  render 'errors/routesError'
            end
      end


      private def algorithm_params
            params.require(:algorithm).permit(:map_id, :form_source, :form_target, :form_autonomy, :form_cost)
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

      #This function show all maps
      def index
            @map = Map.all
      end

      #This function shows the created map
      def show
            @map = Map.find(params[:id])
      end

      #This function create a new map and save in the database
      def create
          @map = Map.create(map_params)
          @map.save

          redirect_to @map
      end

      #This function redirect to the view 'new'
      def new

      end

      #This function implements strong parameters
      private
      def map_params
            params.require(:map).permit(:name)
      end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

      #This function show all routes
      def index
            mapID = params[:id]
            @map = Map.find(mapID)

            @routes = Route.where(map_id: mapID)
      end

      #This function create new route and save it on the database
      def create
             @route = Route.new(route_params)
             @route.save

             redirect_to '/routes/map/'+@route.map_id.to_s
      end

      #This function redirect to the view 'new'
      def new

      end

      #This function implements strong parameters
      private
      def route_params
            params.require(:route).permit(:map_id, :source, :target, :distance)
      end
end

app/helpers/algorithm_helper.rb
module AlgorithmHelper
end

app/helpers/algorithms_helper.rb
module AlgorithmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/algorithms/create.html.erb
<h3>Caminho : <%= @graph.dijkstra(@algorithm.form_source.to_i, @algorithm.form_target.to_i)[:path] %></h3>
<h3>Custo : <%= @algorithm.form_total %></h3>

  <a href="/maps" class="btn btn-danger"><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;&nbsp;Voltar</a>

app/views/algorithms/new.html.erb
<h1>Calcular Gastos</h1>
<hr>
<%= form_for :algorithm, url: '/algorithms/create/' do |f| %>

<div class="row">
<div class="col-md-6">
  <p>
    <input type="hidden" id="algorithm_map_id" name="algorithm[map_id]"  value="<%= params[:id]%>" size="30" type="text">
  </p>
  <p>
    <label>Origem</label><br>
    <%= f.text_field :form_source %>
  </p>

  <p>
    <label>Destino</label><br>
    <%= f.text_field :form_target %>
  </p>

</div>
<div class="col-md-6">
  <p>
      <label>Autonomia</label><br>
      <%= f.text_field :form_autonomy %>
    </p>

    <p>
      <label>Valor da Gasolina</label><br>
      <%= f.text_field :form_cost %>
    </p>

    <p>
      <br>
      <a href="/maps" class="btn btn-danger"><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;&nbsp;Voltar</a>
      <input name="commit" class="btn btn-success" value="Calcular Gasto" type="submit">
    </p>
</div>
</div>



<% end %>

app/views/index/index.html.erb
<h1>Leva e Traz Logística</h1><br><br><br>
<a href="/maps" class="btn btn-success"><i class="glyphicon glyphicon-arrow-right"></i>&nbsp;&nbsp;Mapas</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leva e Traz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container" style="width:50%">
<%= yield %>
</div>


</body>
</html>

app/views/maps/index.html.erb
<h1>Listagem de Mapas</h1>
<hr>
<table class="table table-striped">
<thead>
  <tr>
      <th>ID</th>
      <th>Mapas</th>
       <th>Ações</th>
  </tr>
</thead>
<tbody>
  <% @map.each do |map| %>
    <tr>
      <td><%= map.id  %></td>
      <td><%= map.name %> </td>
      <td><a href = "/routes/map/<%= map.id.to_s %>"><i class="glyphicon glyphicon-eye-open"></i>&nbsp;&nbsp;Ver Rotas</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/algorithms/new/ <%= map.id.to_s  %>"><i class="glyphicon glyphicon-usd"></i>&nbsp;&nbsp;Calcular Custo de Rotas</a></td>
    </tr>
  <% end %>
</tbody>
</table>
<div class="text-right">
  <a href="<%= root_path %>" class="btn btn-danger"><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;&nbsp;Voltar</a>
  <a href="/maps/new" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i>&nbsp;&nbsp;Adicionar Novo Mapa</a>
</div>

app/views/maps/new.html.erb
<h1>Adicionar Novo Mapa</h1>
<hr>
<%= form_for :map, url: maps_path do |f| %>
<div class="row">
      <div class="col-md-6">
            <p>
                <%= f.label :name %><br>
                <%= f.text_field :name %>
              </p>
      </div>
      <div class="col-md-6">
      <br>
            <p>
            <a href="/maps" class="btn btn-danger"><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;&nbsp;Voltar</a>
         <input name="commit"  class="btn btn-success" value="Salvar Mapa" type="submit">
        </p>
      </div>
</div>



<% end %>

app/views/maps/show.html.erb
      <h1>Foi adicionado o mapa de <%= @map.name %></h1>


<a href="/maps" class="btn btn-danger"><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;&nbsp;Voltar</a>

app/views/routes/index.html.erb
<h1>Listagem de Rotas</h1>
<hr>
<table class="table table-striped">
<thead>
  <tr>
    <th>ID do Mapa</th>
    <th>Origem</th>
    <th>Destino</th>
    <th>Distancia</th>
  </tr>
<thead>
<tbody>
  <% @routes.each do |route| %>
    <tr>
      <td><%= route.map_id %></td>
      <td><%= route.source %></td>
      <td><%= route.target %></td>
      <td><%= route.distance %></td>
      <td><a href="<%=route.map_id.to_s%>"></a><td>
    </tr>
  <% end %>
</tbody>
</table>

<div class="text-right">
  <a href="/maps" class="btn btn-danger"><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;&nbsp;Voltar</a>
  <a href="/routes/map/new/<%= params[:id] %>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i>&nbsp;&nbsp;Adicionar Nova Rota</a>
</div>

app/views/routes/new.html.erb
<h1>Adicionar Nova Rota</h1>
<hr>
<%= form_for :route, url: routes_path do |f| %>

<p>
    <input type="hidden" id="route_map_id" name="route[map_id]"  value="<%= params[:id]%>" size="30" type="text">
</p>

<div class="row">
  <div class="col-md-4 text-right"><label>Origem</label></div>
  <div class="col-md-8"><%= f.text_field :source %></div>
</div>
<div class="row">
  <div class="col-md-4 text-right"><label>Destino</label></div>
  <div class="col-md-8"><%= f.text_field :target %></div>
</div>
<div class="row">
  <div class="col-md-4 text-right"><label>Distancia</label></div>
  <div class="col-md-8"><%= f.text_field :distance %></div>
</div>
<div class="row">
  <div class="col-md-4 text-right"></div>
  <div class="col-md-8 ">
<br>
<a href="/maps" class="btn btn-danger"><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;&nbsp;Voltar</a>

  <input name="commit" class="btn btn-success" value="Salvar Rota" type="submit">
</div>
</div>



<% end %>